### PR TITLE
Added Drawing Board to Explore Section

### PR DESCRIPTION
**Pull request by AsmitaMishra24**
Added Drawing Board to Explore Section.
Issue Reference: https://github.com/VaibhavCodeClub/learn/issues/143

Screenshots:-

### CODE REVIEW

**Comment by AsmitaMishra24** [comment]
@sapatevaibhav, I have resolved the merge conflicts, please review the PR

**Comment by AsmitaMishra24** [comment]
Screenshot 2024-05-29 024155

**Review by sapatevaibhav — CHANGES_REQUESTED** [review]
image
There are two cross buttons with same functionality.
Please add white color or eraser (one) ...

**Comment by AsmitaMishra24** [comment]
> image There are two cross buttons with same functionality. Please add white color or eraser (one) ...

ok, I will remove the clear board button and try to add an eraser

**Comment by AsmitaMishra24** [comment]
@sapatevaibhav, I have made the changes as you suggested.

Screenshot 2024-05-31 193819

**Review by sapatevaibhav — APPROVED** [review]

**Pull request merged**
