### PR TITLE
Enhancement in projects folder structure and the folder access strings. #39

### PR DESCRIPTION
**Pull request by Rajkumarbhakta**

### CODE REVIEW

**Comment by Rajkumarbhakta** [comment]
Marge it as soon as possible or it will create marge conflicts @sapatevaibhav

**Comment by sapatevaibhav** [comment]
I am facing lots of issues

**Comment by Rajkumarbhakta** [comment]
please re check everting working fine inside my computer and i re added planet images also. @sapatevaibhav

**Comment by Rajkumarbhakta** [comment]
and please marge this before merging because other contributor may be using different assets path thats why it creating issue.

**Comment by sapatevaibhav** [comment]
Bro I am still getting same errors mentioned on both screens my chrome version too and android too, as well due to this I am going to merge another PR please look into it too...

**Comment by Rajkumarbhakta** [comment]
Have you try flutter clean and then flutter pub get?

**Comment by sapatevaibhav** [comment]
> Have you try flutter clean and then flutter pub get?

Hello the bug is fixed there was a spelling mistake 😐

**Comment by Rajkumarbhakta** [comment]
🙃 okey. I am updating my branch with master please Marge it

**Comment by Rajkumarbhakta** [comment]
@sapatevaibhav conflicts are now resolved

**Pull request merged**
