### PR TITLE
Create LEARN.md

### PR DESCRIPTION
**Pull request by Passionatelytoooadorable**
Completed the assigned task. Please add required labels under GSSoC'24.
Link of issue: https://github.com/VaibhavCodeClub/learn/issues/152

### CODE REVIEW

**Comment by Passionatelytoooadorable** [comment]
> Completed the assigned task. Please add required labels under GSSoC'24. Link of issue: #152

@sapatevaibhav

**Comment by sapatevaibhav** [comment]
Actually I think this Learn.md file is irrelevant to this project.

**Comment by Passionatelytoooadorable** [comment]
> Actually I think this Learn.md file is irrelevant to this project.

Should I prepare another file?

**Comment by sanjay-kv** [comment]
Yes you can ignore the learn.md file, meanwhile I have requested via email to add to this repo. any labelling issue I can handle instantly. @sapatevaibhav

**Pull request closed without merging**
