### PR TITLE
solved issue #120 and #136

### PR DESCRIPTION
**Pull request by hiranj-kotak**

### CODE REVIEW

**Review by sapatevaibhav — CHANGES_REQUESTED** [review]
This is not proper behavior. When I click on any image on the homepage, all the images change height.

**Comment by hiranj-kotak** [comment]
> This is not proper behavior. When I click on any image on the homepage, all the images change height.

okay i will change it asap and can you pls mark the issue under gsoc

**Comment by hiranj-kotak** [comment]
hey @sapatevaibhav i have made the changes pls review it

**Comment by sapatevaibhav** [comment]
Solving multiple issues in single pull will cause problems while distributing scores at GSSoC.

**Comment by hiranj-kotak** [comment]
> Solving multiple issues in single pull will cause problems while distributing scores at GSSoC.
> 

Okay 

Thanks for the information 
And can you pls suggest what should i do now...

**Pull request merged**
