### PR TITLE
added game based  test after learning modules

### PR DESCRIPTION
**Pull request by NamrataCSalvi**
Fixed issues #88 
added fun MCQ tests after animals, birds, flowers, occupations, planets, parts modules

### CODE REVIEW

**Comment by sapatevaibhav** [comment]
image
This issue is there in both the body parts, occupation and birds quiz as well each time first option is the correct one in body quiz.
Option is not clickable only text is make whole container clickable.
As well take quiz for only 5 random things,
Great feature...

**Comment by NamrataCSalvi** [comment]
Thank you for your feedback! I'm glad to inform you that the issues you mentioned have been addressed in the latest update. Now, each set of tests contains 5 random questions. Additionally, the entire button is clickable, and the problem with images has been resolved. Thank you for bringing these concerns to my attention, and I hope you enjoy the improved functionality of the quizzes! If you have any further suggestions, please inform it to me.

**Review by sapatevaibhav — CHANGES_REQUESTED** [review]
There are still some issues 
image
image
Which I don't think are present in master branch.

**Comment by sapatevaibhav** [comment]
Issues are still there try 
```bash
flutter clean
# and then build the app again 
flutter run
``` 
You'll face them

**Comment by sapatevaibhav** [comment]
image

**Pull request closed without merging**
