### PR TITLE
Implemented the landing page for the application and Removed the UI overflow

### PR DESCRIPTION
**Pull request by a-m-a-nkumar**
I have Implemented the landing page for the issue number #124. 
Please review.

I have also resolved issue #129 and eliminated the UI overflow on nearly all pages. Previously, there was UI overflow in landscape view for every popup and on many pages.

I have removed the overflow and made the UI more responsive.

https://github.com/VaibhavCodeClub/learn/assets/99753046/30ed6d05-c48e-4309-84b9-06c5fb855608

### CODE REVIEW

**Comment by a-m-a-nkumar** [comment]
@sapatevaibhav Please review the changes and let me know if you would like to make any adjustments.

**Comment by sapatevaibhav** [comment]
Fix conflicts and mention me I'll merge it ASAP. @a-m-a-nkumar

**Comment by a-m-a-nkumar** [comment]
@sapatevaibhav I have fixed the conflicts.

**Comment by a-m-a-nkumar** [comment]
@sapatevaibhav I have fixed the conflicts.

**Comment by a-m-a-nkumar** [comment]
@sapatevaibhav Please assign the Level tag and GSSOC tag to the pull request and related issue.

**Pull request merged**
