### PR TITLE
Align Explore Page AppBar with Home Page Style

### PR DESCRIPTION
**Pull request by VITianLalit**
This pull request modifies the ExplorePage to ensure that its AppBar is consistent with the AppBar used on the Home Page. Specifically, the scrollable SliverAppBar was replaced with a fixed AppBar.

- Changes Made
__Removed SliverAppBar:__ The SliverAppBar was removed from the ExplorePage.
__Added Fixed AppBar:__ A standard AppBar was added to ensure it remains fixed while the page content scrolls.
__Updated Body Content:__ The main content was encapsulated in a SliverList to maintain the scrollable content area without affecting the fixed AppBar.

https://github.com/VaibhavCodeClub/learn/assets/98540540/b811a59a-03de-4a4b-8276-d5c8388bcc50

@sapatevaibhav ,Please review these changes and merge them into the master branch if everything looks good. Thank you!
fixes issue: Make explore page better #193

### CODE REVIEW

**Comment by sapatevaibhav** [comment]
Screenshot from 2024-06-30 19-38-23
remove option 1 (mentioned in screenshot) as it is same as 3rd one as well make no 2 similar to others like 3 as it doesn't look proper.

**Comment by VITianLalit** [comment]
@sapatevaibhav , oky....

**Comment by VITianLalit** [comment]
@sapatevaibhav , I have made the changes in the explore_page_better branch, kindly review,

image

it is working fine now...

**Comment by VITianLalit** [comment]
fixes issue: Make explore page better #193

**Comment by VITianLalit** [comment]
@sapatevaibhav , Please, let me know, why are you not merging this pull request, Is there any need to do some more changes???

**Comment by sapatevaibhav** [comment]
I'll merge it tonight after testing on my device as I'm busy with some other stuff that is being late😕.
I hope you will understand.

**Comment by VITianLalit** [comment]
Okay, Thanks for informing....

**Pull request merged**
