### PR TITLE
AtoZ_Screen

### PR DESCRIPTION
**Pull request by Prathme07**
Changed the UI, Solved the problem of not flexible with different screen sizes, image problem solved in dark background, removed the rectangle that was coming in background

### CODE REVIEW

**Comment by Prathme07** [comment]
@sapatevaibhav will you please tell me what I have to do to ressolve the conflicts

**Comment by sapatevaibhav** [comment]
> @sapatevaibhav will you please tell me what I have to do to ressolve the conflicts

No need to worry I'll do it.

**Comment by Prathme07** [comment]
@sapatevaibhav Thank you so much

**Review by sapatevaibhav — APPROVED** [review]

**Comment by sapatevaibhav** [comment]
Just do not touch some code like AppConstants and from now on use as it was and add your data there...

**Pull request merged**
