### PR TITLE
Solar System Screen 

### PR DESCRIPTION
**Pull request by Prathme07**
I have created the solar system screen but I am getting difficulty to navigate it to homescreen. Will you please see that and tell me what I have to do to correct that. And I will do that also so please don't it assign to anyone

### CODE REVIEW

**Comment by sapatevaibhav** [comment]
- There isn't any need for main function in that page follow the approach same as other pages.
- Do the essential changes to the drawer,
- As well please go with the SVG files as they take less size try image to SVG converter.

**Comment by Prathme07** [comment]
@sapatevaibhav sorry I didn't see the changes that you adviced now I will do that

**Comment by Prathme07** [comment]
@sapatevaibhav will you please recommend a site to convert png to svg. Cause which I am using either makes all black color or adding black background

**Comment by sapatevaibhav** [comment]
> background

https://www.pngtosvg.com/ 
https://www.flaticon.com/
https://www.svgrepo.com/

**Comment by sapatevaibhav** [comment]
> @sapatevaibhav will you please recommend a site to convert png to svg.

https://www.pngtosvg.com/ 
https://www.flaticon.com/
https://www.svgrepo.com/

**Comment by sapatevaibhav** [comment]
> * There isn't any need for main function in that page follow the approach same as other pages.
> 
>     * Do the essential changes to the drawer,
> 
>     * As well please go with the SVG files as they take less size try image to SVG converter.

First and 3rd thing is not implemented yet here is the code for planet page https://pastebin.com/VXjvXzvc as well from the drawer use
```dart
                Navigator.Named(context, AllRoutes.solarRoute);
```
instead of
```dart
                Navigator.pushReplacementNamed(context, AllRoutes.solarRoute);
```
Such that it doesn't stack as well add this page to home page too. If you have any doubt feel free to get in touch.

**Comment by Prathme07** [comment]
@sapatevaibhav please delete my A to Z screen push from here I don't know much about git so It happened. And please don't remove my solar scree

**Comment by sapatevaibhav** [comment]
Bro there isn't any need of closing PR as everyone here is for learning
things so just keep doing you'll get a lot of things. If you are stuck
everybody is here that is what open source is for.
If you are raising another pull request for the same then you are most
welcome here. 😊
As well focus on exams I'll reserve some issues specially for you.
Keep learning and keep growing. 💪🏼

**Pull request closed without merging**
