### PR TITLE
frutis and Vegetable page added

### PR DESCRIPTION
**Pull request by hiranj-kotak**
Screenshot_1715686454
Screenshot_1715686458
Screenshot_1715686461

### CODE REVIEW

**Comment by hiranj-kotak** [comment]
hey @sapatevaibhav  i have created a pull request for this page please review it and let me know if any changes are needed

**Comment by sapatevaibhav** [comment]
Please resolve the merge conflicts by fetching

**Comment by sapatevaibhav** [comment]
> Please resolve the merge conflicts by fetching

@hiranj-kotak kindly look into it

**Comment by hiranj-kotak** [comment]
Ohhh! Sorry 
I didn't saw this comment 
I will generate new merge request by tomorrow morning

**Pull request closed without merging**
