### PR TITLE
Enhance_UI

### PR DESCRIPTION
**Pull request by Prathme07**

### CODE REVIEW

**Review by Prathme07 — COMMENTED** [review]
Removed the square that was coming when we click on alphabets in A to Z screen

**Comment by sapatevaibhav** [comment]
Hello @Prathme07! You've done great work. Just try to keep the background color of the popup as it was, or change the popup text to adaptive text. In dark mode, the text isn't visible properly.
Screenshot

**Comment by Prathme07** [comment]
Ok I will do that

**Comment by GauravDesale08** [comment]
Hello, I'm interested in contributing to this project. Please assign this to me.

**Comment by Prathme07** [comment]
@sapatevaibhav I have corrected the issue. If any changes needed please inform me

**Comment by sapatevaibhav** [comment]
Merging the PR but still need to change the color of SVG files which are in black color which switching to dark mode.

**Pull request merged**
